Auction/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^register/', include('register.urls')),
    url(r'^login/', include('login.urls')),
    url(r'', include('homepage.urls')),
    url(r'^browse/', include('Browse.urls')),
    url(r'^sell/', include('Sell.urls')),
    url(r'^bids/', include('Bids.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Bids/urls.py
from django.conf.urls import url
from . import views

app_name = 'Bids'
urlpatterns = [

    url(r'^showlistings$', views.show_listings, name='showlist'),
    url(r'^showbids$', views.show_bids, name='showbid'),
    url(r'^showbought$', views.show_bought, name='showbought'),
    url(r'^(?P<item_id>[0-9]+)/$', views.details, name='detail'),
]

Browse/urls.py
from django.conf.urls import url
from . import views

app_name = 'Browse'
urlpatterns = [

    url(r'^show$', views.show, name='show'),
    url(r'^(?P<item_id>[0-9]+)/$', views.details, name='detail'),
    url(r'^(?P<item_id>[0-9]+)/updated$', views.update, name='update'),
    url(r'results$', views.results, name='results'),
]

homepage/urls.py
from django.conf.urls import url, include
from . import views

app_name = 'homepage'
urlpatterns = [

     url(r'^$', views.index, name='index'),
     url(r'^blog$', views.blog, name='blog'),
     url(r'^single$', views.single, name='single'),
     #url(r'^about$', views.about, name='about'),
     #url(r'^register$', include('register.urls')),
     #url(r'^register$', views.register, name='register'),
     #url(r'^login$', include('login.urls')),
]

login/urls.py
from django.conf.urls import url
from . import views
from .views import (login_view,
                    #logout_view,
                    #register_view,
                    # auth_view
                    )

app_name = 'login'
urlpatterns = [

     #url(r'^what$', views.what, name='what'),
     url(r'^$', views.login_view, name='login'),
     url(r'^logout/$', views.logout_view, name='logout')
]

register/urls.py
from django.conf.urls import url
from . import views

app_name = 'register'
urlpatterns = [
    #url(r'^what$', views.what, name='what'),
    #url(r'^registration$', views.registration, name='what'),
    url(r'^$', views.UserFormView.as_view(), name='register'),
]

homepage/models.py
from django.db import models

# Create your models here.

homepage/views.py
from django.shortcuts import render



# Create your views here.

def login(request):
    return render(request, 'login/user_form.html')


def register(request):
    return render(request, 'register/register_form.html')


def index(request):
    active = 'home'
    return render(request, 'homepage/index.html',{'active':active})


def single(request):
    return render(request, 'homepage/single.html')


def blog(request):
    return render(request, 'homepage/blog.html')


def about(request):
    return render(request, 'homepage/index.html')

homepage/templates/homepage/blog.html
<!--Author: W3layouts
Author URL: http://w3layouts.com
License: Creative Commons Attribution 3.0 Unported
License URL: http://creativecommons.org/licenses/by/3.0/
-->
<!DOCTYPE HTML>
<html>
<head>
<title>Auction</title>
{% load staticfiles %}
<link href="{% static 'homepage/bootstrap.css' %}" rel="stylesheet" type="text/css" media="all">
<!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
<script src="{% static 'homepage/jquery-1.11.0.min.js' %}"></script>
<!-- Custom Theme files -->
<link href="{% static 'homepage/style.css' %}" rel="stylesheet" type="text/css" media="all"/>
<!-- Custom Theme files -->
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<script type="application/x-javascript"> addEventListener("load", function() { setTimeout(hideURLbar, 0); }, false); function hideURLbar(){ window.scrollTo(0,1); }>
</script>
<meta name="keywords" content="Auction" />
<!--Google Fonts-->
<link href='http://fonts.googleapis.com/css?family=Lato:100,300,400,700,900' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic' rel='stylesheet' type='text/css'>
<!-- start-smoth-scrolling -->
<script src="http://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
<script type="text/javascript" src="{% static 'homepage/move-top.js' %}"></script>
<script type="text/javascript" src="{% static 'homepage/easing.js' %}"></script>
	<script type="text/javascript">
			jQuery(document).ready(function($) {
				$(".scroll").click(function(event){		
					event.preventDefault();
					$('html,body').animate({scrollTop:$(this.hash).offset().top},1000);
				});
			});
	</script>
</head>
<body>
<!-- //end-smoth-scrolling -->
<!--header start here-->
<div class="header">
	<div class="container">
		<div class="header-main">
			<div class="logo">
				<a href="{% url 'homepage:index' %}"> <img src="{% static 'homepage/images/logo.png' %}" alt="" title=""> </a>
			</div>
			<div class="head-right">
			  <div class="top-nav">
					<span class="menu"> <img src="{% static 'homepage/images/icon.png' %}" alt=""/></span>
				<ul class="res">
					<li><a href="{% url 'homepage:index' %}">Home</a></li>
					<li><a href="{% url 'homepage:index' %}">About Us</a></li>
					<li><a class="active" href="{% url 'homepage:blog' %}">Blog</a></li>
					<li><a href="contact.html">Contact</a></li>
				<div class="clearfix"> </div>
				</ul>
				<!-- script-for-menu -->
							 <script>
							   $( "span.menu" ).click(function() {
								 $( "ul.res" ).slideToggle( 300, function() {
								 // Animation complete.
								  });
								 });
							</script>
			<!-- /script-for-menu -->
			 </div>
		    
			<div class="social">
				<ul >
					<li><a class="fa" href="#"> </a></li>
					<li><a class="tw" href="#"> </a></li>
					<li><a class="p" href="#"> </a></li>
				</ul>
				</div>
			<div class="search-box">
				<div id="sb-search" class="sb-search">
					<form>
						<input class="sb-search-input" placeholder="Search" type="search" name="search" id="search">
						<input class="sb-search-submit" type="submit" value="">
						<span class="sb-icon-search"> </span>
					</form>
			   </div>
			</div>
			<div class="clearfix"> </div>
			   <!-- search-scripts -->
					<script src="{% static 'homepage/classie.js' %}"></script>
					<script src="{% static 'homepage/classie.js' %}"></script>
						<script>
							new UISearch( document.getElementById( 'sb-search' ) );
						</script>
			  <!-- //search-scripts -->
		</div>
		<div class="clearfix"> </div>
		</div>
	</div>
</div>
<!--header end here-->
<!--blog start here-->
<div class="blog">
	<div class="container">
		<div class="blog-main">
			<div class="blog-top">
				<h3>Blog</h3>
				<p>the pain and trouble that are bound to ensue; and equal blame belongs to those who fail in their duty through weakness of will, which is the same as saying through shrinking.</p>
			</div>
			<div class="col-md-9 blog-left">
				<div class="blog-grids">
					<a href="{% url 'homepage:single' %}"><img src="{% static 'homepage/images/blog1.png' %}" alt=""></a>
					<div class="blog-detail">
						<a href="single.html"><h3>Nam libero tempore, cum soluta nobis</h3></a>
						<h4> in <span class="blog-clr">General</span> by Pexeto <span class="blog-clr"> march </span> 3,2015 <span class="blog-clr"> 4 </span> <a href="#">Comments</a> </h4>
						<p>But I must explain to you how all this mistaken idea of denouncing pleasure and praising pain was born and I will give you a complete account of the system, and expound the actual teachings of the great explorer of the truth, the master-builder of human happiness.</p>
						<div class="blog-btn"><a href="single.html">Read More</a></div>
					</div>
				</div>
				<div class="blog-grids">
					<a href="single.html"><img src="images/blog.jpg" alt=""></a>
					<div class="blog-detail">
						<a href="single.html"><h3>Nam libero tempore, cum soluta nobis</h3></a>
						<h4> in <span class="blog-clr">General</span> by Pexeto <span class="blog-clr"> march </span> 3,2015 <span class="blog-clr"> 4 </span> <a href="#">Comments</a> </h4>
						<p>But I must explain to you how all this mistaken idea of denouncing pleasure and praising pain was born and I will give you a complete account of the system, and expound the actual teachings of the great explorer of the truth, the master-builder of human happiness.</p>
						<div class="blog-btn"><a href="single.html">Read More</a></div>
					</div>
				</div>
				<div class="blog-grids">
					<a href="single.html"><img src="images/blog3.jpg" alt=""></a>
					<div class="blog-detail">
						<a href="single.html"><h3>Nam libero tempore, cum soluta nobis</h3></a>
						<h4> in <span class="blog-clr">General</span>  by Pexeto <span class="blog-clr"> march </span> 3,2015  <span class="blog-clr"> 4 </span> <a href="#">Comments</a> </h4>
						<p>But I must explain to you how all this mistaken idea of denouncing pleasure and praising pain was born and I will give you a complete account of the system, and expound the actual teachings of the great explorer of the truth, the master-builder of human happiness.</p>
						<div class="blog-btn"><a href="single.html">Read More</a></div>
					</div>
				</div>
			</div>
			<div class="col-md-3 blog-right">
				<div class="blog-cate">
				<h3>Categories</h3>
				<ul>
					<li><a href="single.html">Featured</a></li>
					<li><a href="single.html">General</a></li>
					<li><a href="single.html">Lorem Ipsum</a></li>
					<li><a href="single.html">literature</a></li>
					<li><a href="single.html">Videos</a></li>
				</ul>
			</div>
			<div class="blog-post">
				<h3>Recent Projects</h3>
				<div class="ftr-gd4-img">
				    <div class="col-md-3 ftr-gd4-1"><a href="single.html"><img src="images/f1.jpg" alt=""></a></div>
				    <div class="col-md-3 ftr-gd4-1"><a href="single.html"><img src="images/f2.jpg" alt=""></a></div>
				    <div class="col-md-3 ftr-gd4-1"><a href="single.html"><img src="images/f3.jpg" alt=""></a></div>
				    <div class="col-md-3 ftr-gd4-1"><a href="single.html"><img src="images/f4.jpg" alt=""></a></div>
				  <div class="clearfix"> </div>
				</div>
				<div class="ftr-gd4-img">
				    <div class="col-md-3 ftr-gd4-1"><a href="single.html"><img src="images/f5.jpg" alt=""></a></div>
				    <div class="col-md-3 ftr-gd4-1"><a href="single.html"><img src="images/f6.jpg" alt=""></a></div>
				    <div class="col-md-3 ftr-gd4-1"><a href="single.html"><img src="images/f7.jpg" alt=""></a></div>
				    <div class="col-md-3 ftr-gd4-1"><a href="single.html"><img src="images/f8.jpg" alt=""></a></div>
				  <div class="clearfix"> </div>
				</div>
				<div class="ftr-gd4-img">
				    <div class="col-md-3 ftr-gd4-1"><a href="single.html"><img src="images/f9.jpg" alt=""></a></div>
				    <div class="col-md-3 ftr-gd4-1"><a href="single.html"><img src="images/f10.jpg" alt=""></a></div>
				    <div class="col-md-3 ftr-gd4-1"><a href="single.html"><img src="images/f11.jpg" alt=""></a></div>
				    <div class="col-md-3 ftr-gd4-1"><a href="single.html"><img src="images/f12.jpg" alt=""></a></div>
				  <div class="clearfix"> </div>
				</div>
			</div>
			</div>
		 <div class="clearfix"> </div>
		</div>
	</div>
</div>
<!--blog end here-->
<!--footer start here-->
<div class="footer">
	<div class="container">
		<div class="footer-main">
			<div class="col-md-3 footer-grid">
				<h3>About This Theme</h3>
				<p>But I must explain to you how all this mistaken idea of denouncing pleasure and praising pain was born and I will give you a complete account of the system, and expound the actual teachings of the great explorer of the truth, the master-builder of human happiness.Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit.account of the system.</p>
			</div>
			<div class="col-md-3 footer-grid">
				<h3>Recents Posts</h3>
			  <div class="ftr-sub-gd">
				<div class="col-md-4 ftr-gd2-img">
					<a href="#"><img src="images/s1.jpg" alt=""></a>
				</div>
				<div class="col-md-8 ftr-gd2-text">
						<a href="#"><h4>How to Have The Best Vacation</h4></a>
						<a href="#"><p>Mar 3rd,2015</p></a>
				</div>
				<div class="clearfix"> </div>
			  </div>
			  <div class="ftr-sub-gd">
				<div class="col-md-4 ftr-gd2-img">
					<a href="#"><img src="images/s2.jpg" alt=""></a>
				</div>
				<div class="col-md-8 ftr-gd2-text">
						<a href="#"><h4>How to Have The Best Vacation</h4></a>
						<a href="#"><p>Mar 3rd,2015</p></a>
				</div>
				<div class="clearfix"> </div>
			  </div>
			  <div class="ftr-sub-gd">
				<div class="col-md-4 ftr-gd2-img">
					<a href="#"><img src="images/s3.jpg" alt=""></a>
				</div>
				<div class="col-md-8 ftr-gd2-text">
						<a href="#"><h4>How to Have The Best Vacation</h4></a>
						<a href="#"><p>Mar 3rd,2015</p></a>
				</div>
				<div class="clearfix"> </div>
			  </div>
		   </div>
			<div class="col-md-3 footer-grid">
				<h3>Categories</h3>
				<ul>
					<li><a href="#">Featured</a></li>
					<li><a href="#">General</a></li>
					<li><a href="#">Lorem Ipsum</a></li>
					<li><a href="#">literature</a></li>
					<li><a href="#">Videos</a></li>
				</ul>
			</div>
			<div class="col-md-3 footer-grid">
				<h3>Recent Projects</h3>
				<div class="ftr-gd4-img">
				    <div class="col-md-3 ftr-gd4-1"><a href="#"><img src="images/f1.jpg" alt=""></a></div>
				    <div class="col-md-3 ftr-gd4-1"><a href="#"><img src="images/f2.jpg" alt=""></a></div>
				    <div class="col-md-3 ftr-gd4-1"><a href="#"><img src="images/f3.jpg" alt=""></a></div>
				    <div class="col-md-3 ftr-gd4-1"><a href="#"><img src="images/f4.jpg" alt=""></a></div>
				  <div class="clearfix"> </div>
				</div>
				<div class="ftr-gd4-img">
				    <div class="col-md-3 ftr-gd4-1"><a href="#"><img src="images/f5.jpg" alt=""></a></div>
				    <div class="col-md-3 ftr-gd4-1"><a href="#"><img src="images/f6.jpg" alt=""></a></div>
				    <div class="col-md-3 ftr-gd4-1"><a href="#"><img src="images/f7.jpg" alt=""></a></div>
				    <div class="col-md-3 ftr-gd4-1"><a href="#"><img src="images/f8.jpg" alt=""></a></div>
				  <div class="clearfix"> </div>
				</div>
				<div class="ftr-gd4-img">
				    <div class="col-md-3 ftr-gd4-1"><a href="#"><img src="images/f9.jpg" alt=""></a></div>
				    <div class="col-md-3 ftr-gd4-1"><a href="#"><img src="images/f10.jpg" alt=""></a></div>
				    <div class="col-md-3 ftr-gd4-1"><a href="#"><img src="images/f11.jpg" alt=""></a></div>
				    <div class="col-md-3 ftr-gd4-1"><a href="#"><img src="images/f12.jpg" alt=""></a></div>
				  <div class="clearfix"> </div>
				</div>
			</div>
		<div class="clearfix"> </div>
		</div>
	</div>
	<div class="copyright">
	<div class="container">
		<div class="copy-main">
			<div class="copy-left">
				<p>Design By<a href="http://w3layouts.com/" target="-blank"> W3layouts</a></p>
			</div>
			<div class="copy-right"> 
				<ul>
					<li><a class="active" href="index.html">Home</a></li>/
					<li><a href="about.html">About</a></li>/
					<li><a href="blog.html">Blog</a></li>/
					<li><a href="contact.html">Contact</a></li>
				</ul>
			</div>
		</div>
	</div>
</div>
</div>
<!--footer end here-->
</body>
</html>

homepage/templates/homepage/index.html
<!--Author: W3layouts
Author URL: http://w3layouts.com
License: Creative Commons Attribution 3.0 Unported
License URL: http://creativecommons.org/licenses/by/3.0/
-->
<!DOCTYPE HTML>
<html>
<head>
<title>Online Auction House</title>

{% load staticfiles %}
<link href="{% static 'homepage/bootstrap.css' %}" rel="stylesheet" type="text/css" media="all">
<!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
{% load staticfiles %}
<script src="{% static 'homepage/jquery-1.11.0.min.js' %}"></script>
<!-- Custom Theme files -->
{% load staticfiles %}
<link href="{% static 'homepage/style.css' %}" rel="stylesheet" type="text/css" media="all"/>
{% load staticfiles %}
<link rel="stylesheet" href="{% static 'homepage/flexslider.css' %}" type="text/css" media="screen" />

<!-- Custom Theme files -->
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<script type="application/x-javascript"> addEventListener("load", function() { setTimeout(hideURLbar, 0); }, false); function hideURLbar(){ window.scrollTo(0,1); }
</script>
<meta name="keywords" content="Auction Responsive web template, Bootstrap Web Templates, Flat Web Templates, AndriodCompatible web template, Smartphone Compatible web template, free webdesigns for Nokia, Samsung, LG, SonyErricsson, Motorola web design" />
<!--Google Fonts-->
<link href="{% static 'homepage/vendor/font-awesome/css/font-awesome.min.css' %}" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet" type="text/css">
    <link href='https://fonts.googleapis.com/css?family=Kaushan+Script' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Droid+Serif:400,700,400italic,700italic' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Roboto+Slab:400,100,300,700' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Lato:100,300,400,700,900' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic' rel='stylesheet' type='text/css'>
<!-- start-smoth-scrolling -->
<script src="http://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
{% load staticfiles %}
<script type="text/javascript" src="{% static 'homepage/move-top.js' %}"></script>
{% load staticfiles %}
<script type="text/javascript" src="{% static 'homepage/easing.js' %}"></script>
	<script type="text/javascript">
			jQuery(document).ready(function($) {
				$(".scroll").click(function(event){		
					event.preventDefault();
					$('html,body').animate({scrollTop:$(this.hash).offset().top},1000);
				});
			});
	</script>
</head>
<body>
<!-- //end-smoth-scrolling -->
<!--header start here-->
<div class="header" style="margin-right:-100px">
	<div class="container">
		<div class="header-main">
			<div class="logo">
				<a href="{% url 'homepage:index' %}"> <img src="{% static 'homepage/images/logo.png' %}" alt="" title=""> </a>
			</div>
			<div class="head-right">
			  <div class="top-nav">
					<span class="menu"> <img src="{% static 'homepage/images/icon.png' %}" alt=""/></span>
				<ul class="res">
					<li><a class="{% if active %}active {% else %} {% endif %}" href="{% url 'homepage:index' %}">Home</a></li>
					<li><a href="#about">About Us</a></li>
                    <li><a  href="{% url 'Browse:show' %}">Browse</a></li>
					<li><a href="{% url 'login:login' %}">Login</a></li>

				<div class="clearfix"> </div>
				</ul>

			 </div>


		</div>
		
		<div class="clearfix"> </div>
		</div>
	</div>
</div>
<!--header end here-->
<!--banner strip start here-->
<script src="{% static 'homepage/responsiveslides.min.js' %}"></script>
<script>
    $(function () {
      $("#slider").responsiveSlides({
      	auto: true,
      	speed: 500,
        namespace: "callbacks",
        pager: false,
        nav:true,
      });
    });
  </script>

<div class="banner1" style="margin-top:0%;">
	<div class="container">
		<div class="banner-main">
			<ul class="rslides callbacks callbacks1" id="slider">
	        <li>
	  			<h3>The Best Place To Buy and Sell</h3>
				<div class="bann-btn">
					  <a href="{% url 'register:register' %}" class="hvr-shutter-out-horizontal">Register</a>
               </div>
	        </li>
	        <li id="callbacks1_s1" class="callbacks1_on" style="float: left; position: relative; opacity: 1; z-index: 2; display: list-item; transition: opacity 500ms ease-in-out;">
	  			<h3>Get your hands on whatever you fancy</h3>
				<p>But this denouncing pleasure and praising</p>
				<div class="bann-btn">
					  <a href="{% url 'register:register' %}" class="hvr-shutter-out-horizontal">Register</a>
               </div>
	        </li>
	        <li id="callbacks1_s2" class="" style="float: none; position: absolute; opacity: 0; z-index: 1; display: list-item; transition: opacity 500ms ease-in-out;">
	        	<h3>Simple procedure, no hassle</h3>
				<div class="bann-btn">
					  <a href="{% url 'register:register' %}" class="hvr-shutter-out-horizontal">Register</a>
               </div>
	        </li>
	      </ul>
			<a href="#" class="callbacks_nav callbacks1_nav prev">Previous</a>
			<a href="#" class="callbacks_nav callbacks1_nav next">Next</a>
		</div>
	</div>
</div>
<div id="about">
		<div class="container">
			<div class="about-main">
				<div class="about-top">
					<h3><strong>A Few Words About Us</strong></h3>
					<h5>This is an online platform dedicated towards creating an auction house experience right at your home. Register, login and quickly find a variety of items to buy and sell at the tip of your fingers! </h5>
				</div>
				<div class="about-text">
					<h3><strong>Top Categories</strong></h3>
					<div class="col-md-4 about-text-left">
						<img src="{% static 'homepage/images/art1.jpg' %}" alt="">
						<h3>Art</h3>
						<p>Rated as the best art provider in city of Mumbai.</p>
					</div>
					<div class="col-md-4 about-text-left">
						<img src="{% static 'homepage/images/clothes.jpg' %}" alt="">
						<h3>Apparel</h3>
						<p>A wide range of clothing accessories including everything from western to indian traditionals.</p>
					</div>
					<div class="col-md-4 about-text-left">
						<img src="{% static 'homepage/images/antique.jpg' %}" alt="">
						<h3>Antique</h3>
						<p>Appreciate the value of historical artifacts and cherish hand picked antiques.</p>
					</div>

					<div class="clearfix"> </div>
				</div>

				<div class="about-text">

					<div class="col-md-4 about-text-left">
						<img src="{% static 'homepage/images/jewellery.jpg' %}" alt="">
						<h3>Jewellery</h3>
						<p>Rated as the best art provider in city of Mumbai.</p>
					</div>
					<div class="col-md-4 about-text-left">
						<img src="{% static 'homepage/images/music.jpg' %}" alt="">
						<h3>Musical Instrument</h3>
						<p>The go to place for exotic musical instruments.</p>
					</div>
					<div class="col-md-4 about-text-left">
						<img src="{% static 'homepage/images/collec.jpg' %}" alt="">
						<h3>Collectible</h3>
						<p>Indulge in your collector's passion and enhance your collections with amazing additions.</p>
					</div>

					<div class="clearfix"> </div>
				</div>
			</div>
		</div>
	</div>

<div class="procedure">
<div class="container">
            <h2><strong>How it works</strong></h2>
            <div class="row">
                <div class="col-lg-3 col-md-6 col-sm-6 maxheight3" style="height: 357px;"><div class="box_inner">
                    <div class="box">
                        <div class="badge fa fa-user " style="font-size: 80px;line-height: 190px;font-family: 'FontAwesome';
    display: block;"></div>
                        <strong>Register</strong>
                        <p>Register yourself and start shopping</p>
                    </div>
                </div></div>
                <div class="col-lg-3 col-md-6 col-sm-6 maxheight3" style="height: 357px;"><div class="box_inner">
                    <div class="box">
                        <div class="badge fa fa-money" style="font-size: 80px;line-height: 190px;font-family: 'FontAwesome';
    display: block;"></div>
                        <strong>Buy or Bid</strong>
                        <p>You Can Buy or Bid any item at a reasonable price</p>
                    </div>
                </div></div>
                <div class="col-lg-3 col-md-6 col-sm-6 maxheight3" style="height: 357px;"><div class="box_inner">
                    <div class="box">
                        <div class="badge fa fa-gavel" style="font-size: 80px;line-height: 190px;font-family: 'FontAwesome';
    display: block;"></div>
                        <strong>Submit a Bid</strong>
                        <p>Submit your bid and wait for the result.</p>
                    </div>
                </div></div>
                <div class="col-lg-3 col-md-6 col-sm-6 maxheight3" style="height: 357px;"><div class="box_inner">
                    <div class="box">
                        <div class="badge fa fa-trophy" style="font-size: 80px;line-height: 190px;font-family: 'FontAwesome';
    display: block;"></div>
                        <strong>Win</strong>
                        <p>If you win,you will receive a notification.Item will be delievered within 8-10 working days.</p>
                    </div>
                </div></div>
            </div>
        </div>
        </div>

</body>
</html>