Auction/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^register/', include('register.urls')),
    url(r'^login/', include('login.urls')),
    url(r'', include('homepage.urls')),
    url(r'^browse/', include('Browse.urls')),
    url(r'^sell/', include('Sell.urls')),
    url(r'^bids/', include('Bids.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Bids/urls.py
from django.conf.urls import url
from . import views

app_name = 'Bids'
urlpatterns = [

    url(r'^showlistings$', views.show_listings, name='showlist'),
    url(r'^showbids$', views.show_bids, name='showbid'),
    url(r'^showbought$', views.show_bought, name='showbought'),
    url(r'^(?P<item_id>[0-9]+)/$', views.details, name='detail'),
]

Browse/urls.py
from django.conf.urls import url
from . import views

app_name = 'Browse'
urlpatterns = [

    url(r'^show$', views.show, name='show'),
    url(r'^(?P<item_id>[0-9]+)/$', views.details, name='detail'),
    url(r'^(?P<item_id>[0-9]+)/updated$', views.update, name='update'),
    url(r'results$', views.results, name='results'),
]

Sell/urls.py
from django.conf.urls import url
from . import views

app_name = 'Sell'
urlpatterns = [

    url(r'^$', views.ItemUploadFormView.as_view(), name='upload'),
    #url(r'^what$', views.what, name='what'),

]

homepage/urls.py
from django.conf.urls import url, include
from . import views

app_name = 'homepage'
urlpatterns = [

     url(r'^$', views.index, name='index'),
     url(r'^blog$', views.blog, name='blog'),
     url(r'^single$', views.single, name='single'),
     #url(r'^about$', views.about, name='about'),
     #url(r'^register$', include('register.urls')),
     #url(r'^register$', views.register, name='register'),
     #url(r'^login$', include('login.urls')),
]

login/urls.py
from django.conf.urls import url
from . import views
from .views import (login_view,
                    #logout_view,
                    #register_view,
                    # auth_view
                    )

app_name = 'login'
urlpatterns = [

     #url(r'^what$', views.what, name='what'),
     url(r'^$', views.login_view, name='login'),
     url(r'^logout/$', views.logout_view, name='logout')
]

Browse/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.contrib.auth.models import User
from django.db import models
from django.utils.timezone import localtime, now


class Items(models.Model):
    seller = models.ForeignKey(User, null=True)
    item_id = models.AutoField(primary_key=True)
    item_logo = models.FileField(null=True, blank=True)
    item_name = models.CharField(max_length=2500)
    item_desc = models.TextField(max_length=2500)
    cur_highest_bidder = models.ForeignKey(User, related_name="highest_bidder", null=True, blank=True)
    cur_highest_bid = models.IntegerField(null=True, default=0)
    created_on = models.DateTimeField(null=True)
    expiration = models.DateTimeField(null=True)
    min_price = models.IntegerField(null=True)
    buy_now_price = models.IntegerField(null=True)

    def __str__(self):
        return self.item_name
# Create your models here.


class Bought(models.Model):
    seller = models.ForeignKey(User, null=True)
    item_id = models.AutoField(primary_key=True)
    item_logo = models.FileField(null=True, blank=True)
    item_name = models.CharField(max_length=2500)
    item_desc = models.TextField(max_length=2500)
    buyer = models.ForeignKey(User, related_name="buyer", null=True, blank=True)
    cur_highest_bid = models.IntegerField(null=True, default=0)
    created_on = models.DateTimeField(null=True)
    expiration = models.DateTimeField(null=True)
    min_price = models.IntegerField(null=True)
    buy_now_price = models.IntegerField(null=True)
    #sell_price = models.IntegerField(null=True, default=0)

    def __str__(self):
        return self.item_name


class Expired(models.Model):
    seller = models.ForeignKey(User, null=True)
    item_id = models.AutoField(primary_key=True)
    item_name = models.CharField(max_length=2500)
    item_desc = models.TextField(max_length=2500)
    created_on = models.DateTimeField(default=localtime(now()))
    min_price = models.IntegerField(null=True)
    buy_now_price = models.IntegerField(null=True)

    def __str__(self):
        return self.item_name

Browse/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from datetime import date, datetime
from time import localtime

from django.utils import timezone
from django.conf import settings
from .models import Items, Expired, Bought
from Bids.models import Credits
from django.shortcuts import render,redirect
from django.contrib.auth import get_user_model
from django.contrib import messages
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.core.mail import send_mail,EmailMessage
from django.http import HttpResponse
# Create your views here.

User = get_user_model()

def show(request):
    if request.user.is_authenticated:
        exp = Expired()
        bt = Bought()
        for i in Items.objects.all():
            if i.cur_highest_bid!=0 and i.expiration < timezone.now():
                item = Items.objects.get(pk=i.item_id)
                bt.seller = item.seller
                bt.item_id = item.item_id
                bt.item_logo = item.item_logo
                bt.item_name = item.item_name
                bt.item_desc = item.item_desc
                bt.buyer = item.cur_highest_bidder
                bt.cur_highest_bid = item.cur_highest_bid
                bt.created_on = item.created_on
                bt.expiration = item.expiration
                bt.min_price = item.min_price
                bt.buy_now_price = item.buy_now_price
                bt.save()
                exp.seller = item.seller
                exp.item_id = item.item_id
                exp.item_name = item.item_name
                exp.item_desc = item.item_desc
                exp.created_on = item.created_on
                exp.min_price = item.min_price
                exp.buy_now_price = item.buy_now_price
                exp.save()
                item.delete()

            elif i.expiration < timezone.now():
                item = Items.objects.get(pk=i.item_id)
                exp.seller = item.seller
                exp.item_id = item.item_id
                exp.item_name = item.item_name
                exp.item_desc = item.item_desc
                exp.created_on = item.created_on
                exp.min_price = item.min_price
                exp.buy_now_price = item.buy_now_price
                exp.save()
                item.delete()

            #elif i.cur_highest_bid == i.buy_now_price:
             #   i.delete()

        all_items_list = Items.objects.all()
        page = request.GET.get('page', 1)

        paginator = Paginator(all_items_list, 8)
        try:
            all_items = paginator.page(page)
        except PageNotAnInteger:
            all_items = paginator.page(1)
        except EmptyPage:
            all_items = paginator.page(paginator.num_pages)
        user_name = User.objects.get(username=request.user.username)
        credits = Credits.objects.get(name=user_name)
        score = credits.credit
        context = {
            'all_items': all_items,
            'score':score,
            'user_name':user_name,
        }
        return render(request, 'Browse/index.html', context)
    else:
        return redirect('login:login')


def details(request, item_id):
    cur_item = Items.objects.get(pk=item_id)
    user_name = User.objects.get(username=request.user.username)
    credits = Credits.objects.get(name=user_name)
    score = credits.credit
    context = {
        'cur_item': cur_item,
        'score':score,
    }
    return render(request, 'Browse/details.html', context)


def update(request, item_id):
    all_items = Items.objects.all()
    cur_item = Items.objects.get(pk=item_id)
    user_name = User.objects.get(username=request.user.username)
    print(user_name)
    credits = Credits.objects.get(name=user_name)
    c1 = Credits.objects.get(name=cur_item.seller)
    score = credits.credit
    # print(credits)
    bid = request.POST['bid_value']
    if int(score) >= int(bid):
        html_content = "<strong>Your current bid has been overtaken by someone.</strong>"
        email = EmailMessage('Auction House:Sad news', html_content, to=['jainamsoni33@gmail.com'])
        email.content_subtype = "html"
        email.send()
        if int(bid) in range(int(cur_item.cur_highest_bid), int(cur_item.buy_now_price)) and int(bid) > cur_item.min_price:

            cur_item.cur_highest_bid = bid
            cur_item.cur_highest_bidder = User.objects.get(username=request.user.username)
            cur_item.save()
            #credits.credit = int(credits.credit) - int(bid)
            #credits.save()
            #c1.credit = int(c1.credit) + int(bid)
            #c1.save()

            context = {
                'all_items': all_items,
            }
            return render(request, 'Browse/index.html', context)
        elif int(bid) >= int(cur_item.buy_now_price):
            cur_item.cur_highest_bid = bid
            cur_item.cur_highest_bidder = User.objects.get(username=request.user.username)
            credits.credit = int(credits.credit) - int(bid)
            credits.save()
            c1.credit = int(c1.credit) + int(bid)
            c1.save()
            cur_item.save()
            bt = Bought()
            bt.seller = cur_item.seller
            bt.item_id = cur_item.item_id
            bt.item_logo = cur_item.item_logo
            bt.item_name = cur_item.item_name
            bt.item_desc = cur_item.item_desc
            bt.buyer = cur_item.cur_highest_bidder
            bt.cur_highest_bid = cur_item.cur_highest_bid
            bt.created_on = cur_item.created_on
            bt.expiration = cur_item.expiration
            bt.min_price = cur_item.min_price
            bt.buy_now_price = cur_item.buy_now_price
            bt.save()
            cur_item.delete()
            messages.error(request, 'Congrats, you won!.')
            #messages.error(request, 'Congrats, you won!.')
            #cur_item = Items.objects.all()
            #cur_item = Items.objects.get(pk=item_id)
            context = {
                 'all_items': all_items,
            }

            return render(request, 'Browse/index.html', context)
        elif int(cur_item.cur_highest_bid) > int(bid) or int(cur_item.min_price) > int(bid):

            messages.error(request, 'Bid rejected.')
            cur_item = Items.objects.get(pk=item_id)
            context = {
                'cur_item': cur_item
            }
            return render(request, 'Browse/details.html', context)

    elif int(score) < int(bid):
        messages.error(request, 'You do not have enough credits!')
        cur_item = Items.objects.get(pk=item_id)
        context = {
            'cur_item': cur_item
        }
        return render(request, 'Browse/details.html', context)


def results(request):
    query = request.GET.get('search')
    item_list = Items.objects.filter(item_name__icontains=query)
    print(item_list)
    return render(request, 'Browse/index.html', {'all_items':item_list})

Browse/templates/Browse/base.html
<!DOCTYPE HTML>
<html>
<head>
<title>Online Auction House</title>
{% load staticfiles %}
<script>try{Typekit.load({ async: true });}catch(e){}</script>
<link rel="stylesheet" href="{% static 'Browse/styledetail.css' %}">
{% load staticfiles %}
<link href="{% static 'homepage/bootstrap.css' %}" rel="stylesheet" type="text/css" media="all">
<!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
{% load staticfiles %}
<script src="{% static 'homepage/jquery-1.11.0.min.js' %}"></script>
<!-- Custom Theme files -->
{% load staticfiles %}
<link href="{% static 'homepage/style.css' %}" rel="stylesheet" type="text/css" media="all"/>
{% load staticfiles %}
<link rel="stylesheet" href="{% static 'homepage/flexslider.css' %}" type="text/css" media="screen" />

<!-- Custom Theme files -->
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<script type="application/x-javascript"> addEventListener("load", function() { setTimeout(hideURLbar, 0); }, false); function hideURLbar(){ window.scrollTo(0,1); }
</script>
<meta name="keywords" content="Auction Responsive web template, Bootstrap Web Templates, Flat Web Templates, AndriodCompatible web template, Smartphone Compatible web template, free webdesigns for Nokia, Samsung, LG, SonyErricsson, Motorola web design" />
<!--Google Fonts-->
<link href="{% static 'homepage/vendor/font-awesome/css/font-awesome.min.css' %}" rel="stylesheet" type="text/css">
<link href="https://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet" type="text/css">
<link href='https://fonts.googleapis.com/css?family=Kaushan+Script' rel='stylesheet' type='text/css'>
<link href='https://fonts.googleapis.com/css?family=Droid+Serif:400,700,400italic,700italic' rel='stylesheet' type='text/css'>
<link href='https://fonts.googleapis.com/css?family=Roboto+Slab:400,100,300,700' rel='stylesheet' type='text/css'>
<link href='https://fonts.googleapis.com/css?family=Lato:100,300,400,700,900' rel='stylesheet' type='text/css'>
<link href='https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic' rel='stylesheet' type='text/css'>
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,600">
<link rel="stylesheet" href="{% static 'Browse/hero-slider-style.css' %}">
<link rel="stylesheet" href="{% static 'Browse/magnific-popup.css' %}">
<link rel="stylesheet" href="{% static 'Browse/templatemo-style.css' %}">
<link rel="stylesheet" href="{% static 'Browse/Font-Awesome-4.7/css/font-awesome.min.css' %}">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
{% load staticfiles %}
<link href="{% static 'homepage/bootstrap.css' %}" rel="stylesheet" type="text/css" media="all">
<!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
{% load staticfiles %}
<script src="{% static 'homepage/jquery-1.11.0.min.js' %}"></script>
<!-- Custom Theme files -->
{% load staticfiles %}
<link href="{% static 'Browse/style.css' %}" rel="stylesheet" type="text/css" media="all"/>
{% load staticfiles %}
<link rel="stylesheet" href="{% static 'homepage/flexslider.css' %}" type="text/css" media="screen" />
{% load staticfiles %}
<script type="text/javascript" src="{% static 'homepage/move-top.js' %}"></script>
{% load staticfiles %}
<script type="text/javascript" src="{% static 'homepage/easing.js' %}"></script>
<script type="text/javascript" src="{% static 'Browse/js/jquery-1.11.3.min.js' %}"></script>

	<script type="text/javascript">
			jQuery(document).ready(function($) {
				$(".scroll").click(function(event){
					event.preventDefault();
					$('html,body').animate({scrollTop:$(this.hash).offset().top},1000);
				});
			});
	</script>
</head>
<body >
<div class="header">
	<div class="container">
		<div class="header-main">
			<div class="logo">
				   <form class="navbar-form navbar" role="search" method="get" action="{% url 'Browse:results' %}" style="margin-top:-10px">
					   <div class="form-group" style="float:left">
                           <ul class="res" style="margin: 0;
    padding: 0;
    list-style-type: none;
    min-width: 200px;
    float: left;
    display: inline;">

                          <li class="fa fa-google-wallet" aria-hidden="true" style="font-size: 1.5em;color:#0ab2d;background-color:#0ab2d"><a style="color:white">  My Wallet:{{ score }}</a></li>
							   <li style="padding-left:250px"><input type="text" class="form-control" placeholder="{{ user_name }} ,Search here" name="search" value="" required="true">
							   <button type="submit" class="btn" style="background-color:#0ab2d2;color:black">Search</button></li>
						   </ul>
					   </div>
                       <!--<li><input type="text" class="form-control" placeholder="{{ user_name }} ,Search here" name="search" value="" required="true">-->
							   <!--<button type="submit" class="btn" style="background-color:#0ab2d2;color:black">Search</button></li>-->

				   </form>

			</div>
			<div class="head-right">

			  <div class="top-nav">
									<ul class="res">
					<li><a href="{% url 'homepage:index' %}">Home</a></li>
					<li><a href="{% url 'Sell:upload' %}">Upload</a></li>
                    <li><a href="{% url 'Bids:showlist' %}">My Listings</a></li>
                    <li><a href="{% url 'Bids:showbid' %}">My Bids</a></li>

                    <li>
                        <a  href="{% url 'login:logout' %}">Logout
                        </a>
                    </li>

                 </ul>
              </div>
             </div>
         </div>
    </div>
</div>
{% block body  %}
{% endblock %}

Browse/templates/Browse/details.html
{% extends 'Browse/base.html' %}
{% load staticfiles %}
<link rel="stylesheet" href="{% static 'Browse/styledetail.css' %}">
{% block item_active %}active{% endblock %}
{% block body  %}

{% if cur_item %}

    <div id="wrapper" style="padding-top: 20px">
      <div id="container" style=" height: 80%; width: 80% ">

        <div id="info">
          <div id="product-img">
            <img id="product" src="{{ cur_item.item_logo.url }}" style="max-width:100%;max-height:480px; margin-left:50px; margin-top:50px;">
          </div>

          <div id="price">
            <h2>{{cur_item.item_name}}</h2>
            <h2>$ {{cur_item.min_price}}</h2>

          </div>
        </div>


        <div id="payment" style="padding:0px">

          <form id="checkout" action="{% url 'Browse:update' cur_item.item_id %}" method="POST">
            {% csrf_token %}
            <!--<input class="card" id="visa" type="button" name="card" value="">
            <input class="card" id="mastercard" type="button" name="card" value="">-->

            <label>Created on</label>
            <input id="cardnumber" type="text"  name="cardname" maxlength="50" value="{{cur_item.created_on}}" readonly>
            <div ></div>
            <label>Seller &nbsp &nbsp</label>
           <input id="cardholder" type="text" name="name"  maxlength="50" value="{{cur_item.seller}}" readonly>
            <label>Min Price</label>
           <input id="cardholder3" type="text" name="name"  maxlength="50" value="{{cur_item.min_price}}" readonly>

            <label>Current highest bidder</label>
           <input id="cardholder1" type="text" name="name"  maxlength="50" value="{{cur_item.cur_highest_bidder}}" readonly>

            <label>Current highest bid</label>
           <input id="cardholder2" type="text" name="name"  maxlength="50" value="{{cur_item.cur_highest_bid}}" readonly>

            <label>Buy Now</label>
           <input id="cardholder3" type="text" name="name"  maxlength="50" value="{{cur_item.buy_now_price}}" readonly>

            <label>Expiration Date</label>
            <input id="cardholder4" type="text" name="name"  maxlength="50" value="{{ cur_item.expiration }}" readonly>

             <label>Enter your bid</label>
              <input id = "bid" type="text" name="bid_value">
             <button type="submit" class="btn" align="center">Submit Bid</button>
           </form>
        </div>

        </div>
      </div>
    {% if messages %}
        <script>

                {% for message in messages %}
                  alert("{{ message }}")
                {% endfor %}

        </script>
    {% endif %}
{% else %}
    <h1>YOU DON'T HAVE ANY ITEMS</h1>
{% endif %}
{% endblock %}

Browse/templates/Browse/index.html
{% extends 'Browse/base.html' %}
{% block item_active %}active{% endblock %}
{% block body %}
    <div class="cd-hero">
        <ul class="cd-hero-slider">
            <li class="selected">
                <div class="container-fluid js-tm-page-content" data-page-no="1" data-page-type="gallery" style="padding-left:0px">
                    <div class="tm-img-gallery-container">

                            {% if all_items %}
                                {% for item in all_items %}
                                    <div class="grid-item" style="margin-bottom: 50px;">
                                        <a href="{% url 'Browse:detail' item.item_id %}" >
                                        <figure class="effect-sadie">
                                            <img src="{{ item.item_logo.url }}" alt="Image" class="img-fluid tm-img">

                                            <figcaption>
                                                <h4 class="tm-figure-title" style="margin-bottom: 0;color: white;text-shadow: 2px 2px 6px #000;font-weight: 400;
font-size: 1.5rem;
position: absolute;
top: 50%;
left: 0;
width: 100%;transform: translate3d(0,-50%,0);color:black">{{item.item_name}}</h4>
                                                <p class="tm-figure-description">{{ item.item_desc}}</p>
                                            </figcaption>
                                        </figure>
                                        </a>
                                    </div>
                                {% endfor %}

                    </div>
                </div>
            </li>
        </ul>
    </div>
        <div class="clearfix visible-lg"></div>
        {% if all_items.has_other_pages %}
          <ul class="pagination">
            {% if all_items.has_previous %}
              <li><a href="?page={{ all_items.previous_page_number }}">&laquo;</a></li>
            {% else %}
              <li class="disabled"><span>&laquo;</span></li>
            {% endif %}
            {% for i in all_items.paginator.page_range %}
              {% if all_items.number == i %}
                <li class="active"><span>{{ i }} <span class="sr-only">(current)</span></span></li>
              {% else %}
                <li><a href="?page={{ i }}">{{ i }}</a></li>
              {% endif %}
            {% endfor %}
            {% if all_items.has_next %}
              <li><a href="?page={{ all_items.next_page_number }}">&raquo;</a></li>
            {% else %}
              <li class="disabled"><span>&raquo;</span></li>
            {% endif %}
          </ul>
        {% endif %}
    {% else %}
        <h2> Sorry no Items to Display.</h2>
    {% endif %}
{% load staticfiles %}
<script src="{% static 'Browse/js/tether.min.js' %}"></script>
<script src="{% static 'Browse/js/bootstrap.min.js' %}"></script>
<script src="{% static 'Browse/js/hero-slider-main.js' %}"></script>
<script src="{% static 'Browse/js/jquery.magnific-popup.min.js' %}"></script>
<script>

            function adjustHeightOfPage(pageNo) {

                var pageContentHeight = 0;

                var pageType = $('div[data-page-no="' + pageNo + '"]').data("page-type");

                if( pageType != undefined && pageType == "gallery") {
                    pageContentHeight = $(".cd-hero-slider li:nth-of-type(" + pageNo + ") .tm-img-gallery-container").height();
                }
                else {
                    pageContentHeight = $(".cd-hero-slider li:nth-of-type(" + pageNo + ") .js-tm-page-content").height() + 20;
                }

                // Get the page height
                var totalPageHeight = $('.cd-slider-nav').height()
                                        + pageContentHeight
                                        + $('.tm-footer').outerHeight();

                // Adjust layout based on page height and window height
                if(totalPageHeight > $(window).height())
                {
                    $('.cd-hero-slider').addClass('small-screen');
                    $('.cd-hero-slider li:nth-of-type(' + pageNo + ')').css("min-height", totalPageHeight + "px");
                }
                else
                {
                    $('.cd-hero-slider').removeClass('small-screen');
                    $('.cd-hero-slider li:nth-of-type(' + pageNo + ')').css("min-height", "100%");
                }
            }

            /*
                Everything is loaded including images.
            */

            $(window).load(function(){

                adjustHeightOfPage(1); // Adjust page height

                /* Gallery One pop up
                -----------------------------------------*/
                $('.gallery-one').magnificPopup({
                    delegate: 'a', // child items selector, by clicking on it popup will open
                    type: 'image',
                    gallery:{enabled:true}
                });


                /* Collapse menu after click
                -----------------------------------------*/
                $('#tmNavbar').find('a').click(function(){
                    $('#tmNavbar').collapse('hide');

                    adjustHeightOfPage($(this).data("no")); // Adjust page height
                });

                /* Browser resized
                -----------------------------------------*/
                $( window ).resize(function() {
                    var currentPageNo = $(".cd-hero-slider li.selected .js-tm-page-content").data("page-no");

                    // wait 3 seconds
                    setTimeout(function() {
                        adjustHeightOfPage( currentPageNo );
                    }, 1000);

                });

                // Remove preloader (https://ihatetomatoes.net/create-custom-preloading-screen/)
                $('body').addClass('loaded');

                // Write current year in copyright text.
                $(".tm-copyright-year").text(new Date().getFullYear());

            });


</script>
{% endblock %}

Browse/templates/Browse/something.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <h1>BID registered</h1>
</body>
</html>

Browse/templates/Browse/trial.html
{% load staticfiles %}

{% if bid %}
    <h1>value is {{ bid }}</h1>
{% endif %}